######################################################################
# Automatically generated by qmake (2.00a) mar. 3. oct. 20:11:06 2006
######################################################################

TEMPLATE = lib
CONFIG += dll
TARGET += 
DEPENDPATH += . fx2
INCLUDEPATH += .

# Input
HEADERS += CypressEzUSBDevice.h \
           ezusbsys.h \
           USBDevice.h \
           fx2/ezusbsys.h \
           fx2/usb100.h
SOURCES += CypressEzUSBDevice.cpp 